#+TITLE: Реализовать на С++ концепцию векторной ф-ции скалярного аргумента (с привлечением механизма наследования и виртуальных ф-ций).
* TODO Написать код
** TODO Написать структруру базового класса, выполнить наследование
- [X] Разобраться с ключ. словом virtual.
- [X] Сформировать вектор из ф-ций выранных пользователем ф-ций пользовательского размера.
- [X] Сделать красивый вывод для каждого из производных классов.
  + Для этого : класс должен хранить параметры ф-ций.
- [X] Для универсальности и расширяемости Хранить параметры и результат выражение в классе.  
- [ ] Выполнить обработку ошибок ввода с помощью regex и исключений.
* TODO Ответить на контрольные и вознишие в ходе выполнения работы вопросы. Начал : <2023-10-10 Tue>
** TODO ?! Зачем используются модификаторы при наследовании классов, какие это модификаторы
** TODO ?! Зачем нужен механизм наследования.
- Наследование :: Механизм, который позволяет описать на основе уже существующего, с частично или полностью заимствованной функциональность.
  + Режимы наследования в С++ :: открытый : открытые члены базового класса остаются открытыми в производном классе, закрытый : все члены базового класса становятся закрытыми членами производного класса, защищенный : все открытые члены базового класса становятся защищенными членами производного класса.
- Для создания иерархической структуры классов, которая позволяет достичь оптимального управления моделью реального объекта. Для этого на каждом иерархическом шаге учитываются только изменения, чтобы не дублировать свойства и методы, учтенные на предыдущих шагах.
** TODO ?! Зачем нужен механизм полиморфизма И какие сущ. виды полиморфизма, к какому из видом полиморфизма относится перегрузка оператора
- [ ] Дать понятное определение полиморфизма, опираясь на лекцию Ведуна.
** TODO ?! Что такое интерфейс класса
** TODO ?! Зачем нуже чисто виртуальный метод
** TODO ?! Какой класс называется абстрактным
