* Терминология

- Командный процессор :: **программа,** которая принимает команды вводимые с клавиатуры и передает их **операционной системе** для выполнения.

- Expansion :: Раскрытие выражений.
- Shell prompt :: Приглашение командного процессора

* Кавычки двойные и одинарные

! Кавычки задают литерал - последовательность символов, котору командный процессор не должен анализировать или изменять перед передачей в качестве входных данных вызываемым программам.

- Одинарные кавычки :: Задают строковый литерал, все символы между ними оцениваются как один параметр.
- Двойные кавычки :: Тоже задают литерал, НО командный процессор выполняет подстановку значений всех переменных.
* Операции с переменными

| Оператор | Операция                                                  |
|----------+-----------------------------------------------------------|
| ~$~      | Доступ к переменной                                       |
| ~$()~    | Сохранить выходные данные программы в качестве пеерменной |
| ~$(())~    | Вычислить арифметическое выражение                        |
