#+startup: overview
#+startup: num
* Ресурсы

1. Герберт Шидт - Java Полное руководство
2. Крейг Уоллс - Spring в действии

* Ход работы

Чтобы избежать проблем во время сборки классы следует хранить в главном пакете каталога ~/src/java~.

** Этапы

2. Реализация базового функционала

3. Подключение базы данных Postgre SQL, разделение функционала бота.

4. Обработка ошибок, настройка автоматических тестов

** Вопросы

** Задачи [0/2]

*** TODO [#A] ЛР №2 Запустить, добавить кнопки, реализовать команды, не зависящие от базы данных
DEADLINE: <2023-12-09 Sat>

- [X] Разобраться с обработкой исключений
- [ ] Разобраться с настройкой меню бота, добавить кнопки

- [X] Разобраться с пакетами, аннотациями и интерфейсами.

- [ ] Отправить отчет Тюрину.

*** TODO Подключить б/д и реализовать их функционал.

- [X] Получить исполняемый jar-файл
- [ ] Установить postgre и подключить все необходимые зависимости.

- [ ] Отправить отчет Тюрину.

*** Закинуть бота на Linux сервер, подключить базу данных.


* Теор материал

** Терминология

- Зависимость :: Одно из отношение между объектами в терминах ООП, один объект каким то образом ссылается на другой.

- bean :: Компонент объектной модели JavaBeans. Контейнер объекта некоторого класса, который создается и обслуживается Spring

- classpath :: Каталог, в котором осуществляется поиск классов.

- Spring Boot :: Расширение фреймворка Java Spring, используется для создания микросервисов. Предоставляет :
  1. Автоконфигурацию, механизм, который позволяет автоматизировать управление контекстом приложения.
  2. Автоматизацию сборки зависимостей
  3. Мониторинг времени выполнения.

- Микросервис :: Маленькая веб-служба выполняет определенные задачи И взаимодействует с другими веб-службами.
  + (разделяй и властвуй) Позволяют разбить большое, сложное монолитное приложение на маленькие, логически независимые модули, что существенно упрощает процессы : разработки, тестирования и развертывания.
  + Приложения на основе микросервисов размещаются в облаке.

- Вебхук == веб-перехватчик :: Механизм получения одним приложением в режиме реального времени информации о событиях, происходящих в другом приложении.
  + Сервер c вебхуком автоматически отправляет клиенту полезную информацию всякий раз когда на серверном приложении происходит определенное событие.
  + Использует протокол HTTP или HTTPS.
    * В целях защиты соединения полезные данные хешируют.

- Контроллер :: Класс, обрабатывает запросы и возвращает некотрорую информацию.

- jar :: Архивный файл приложения на языке Java. Используется для хранения приложения Java в одном файле, состоит из скомпилированных в байт-код классов, списка ресурсов и ресурсов приложения.
  + В момент запуска jar файла вызывается метод main - точка входа в программу.

- logger :: Средство ведения журнала


** Тг бот

- Бот :: Особая учетная запись, небольшое приложение, которое запускается внутри приложения Телеграм, используюет сообщения в качестве входных данных.
  + Главная ф-ция :: отправлять и получать сообщения.
    * Может писать в лс только тем пользователям, которые его запустили.
    * Отправляет запросы на Телеграм и получает от него обновления.
    * Пишутся на Java, js, python с использованием Telegram Bot API или Telegram API (используется больше для создания своего клиента Телеграм) И библиотек.

Создать и настроить бота можно через спец. бота BotFather, он выдает уникальный идентификатор бота, он используется для управления созданным ботом.

Чтобы бот был всегда доступен jar файл приложения нужно запусть на linux-сервере.

** Slf4j фасадный метод для различных фрейворков ведения журналов.

Аннотация ~@ Slf4j~ создает объект ~log~

Средство ведения журнала (логгер) настраивают в XML файле ~/src/main/resources/logback.xml~.

Логгер фиксирует всю информацию в консоли.


** Средство автоматизации сборки Gradle

Плагины добавляют новые задачи (tasks), которые выполняют компиляцию кода или выполнение тестов.

Зависимость - внешний модуль (фреймворк, библиотека, плагин), необходимый на одном из этапов разработки ПО.
- Объявляется в блоке dependencies.

Конфигурация зависимости определяет этап разработки, на котором она будет задействована : компиляции, сборки, тестирования.

- stater :: Набор связанных зависимостей определенной версии.

Чтобы объявить зависимость на языке gradle-groovy нужно :

1. Выбрать конфигурацию :
   - implementation :: Зависимость необходима на этапе компиляции. Включается в переменную среды окружения classpath.
   - compileOnly :: Зависимость необходима на этапе компиляции. Не включается в classpath.
2. Описать зависимость. Зависимость описывается 4 ключами : группы, имени и версии.

Сгенерировать исполняемый jar файл можно с помощью скрипта ~shadow jar~, полученный файл находится в каталоге ~/build/libs/~

** Система управления реляционными базами данных PostgreSQL.

Стандартный порт : 5432.


** Фреймворк Spring

REST для микросервисов, мне пока не нужен.

*** Что вообще делает Spring

Используется везде, где используется Java, просто упрощает разработку приложений.

Spring :: Самый популярный Java фреймворк, облегчает разработку,

**** Позволяет автоматизировать управление зависимостями

Т. е. не создавать вручную миллион экземпляров используемых классов.

Используемые классы аннотируют чтобы Spring автоматически создал их экземпляры в момент запуска приложения.

Создает контекст приложения и обеспечивает удобный доступ к б/д.

Контекст приложения Spring - Специальный объект (контейнер), который создает компоненты приложения и внедряет их в другие, зависящие от них компоненты с помощью констурктора или геттеров.


**** Инъекция зависимостей - процесс объединения bean-компонентов - Контекст приложения и автоконфигурация

Механизм, который позволяет построить дерево зависимостей и поместить один класс внутрь другого.

Spring создает контейнер == *контекст приложения*, в котором создает необходимые объекты классов (компоненты), из которых состоит приложение и управляет их жизненным циклом.
- Контекстом приложения управляют с помощью XML-файлов (устаревший способ), так и с помощью спец. класса конфигурации (актуальный способ).

Автоконфигурация включает : связывание компонетов и внедрение свойств.



*** Структура проекта Java Spring

- Spring Tool Suite :: среда разработки на Spring, расширение для vs code.

- Spring Initializr :: Инструмент инициализации проекта на Spring Boot, Предоставляет REST API.

- Gradle :: Высокопроизводительный иструмент для автоматизации сборки приложений. Выполняется на виртуальной машине Java. Лучше чем Maven.
  + Зависимости добавляются в файл ~build.gradle~.
    - Зависимости :: Модули, библиотеки, необходимые для компиляции приложения.

    - Объявление зависимостей : 1 - в виде строки, 2 - в виде структуры, сост. из пар ключ-значение : группа, имя, версия.
    - Типы зависимостей : 1 - implementation -> используется только для компиляции приложения.

**** test

Каталог ~/src/test/~ предназначен для автоматических тестов.

**** main

Каталог ~resources~ содержит статические ресурсы (таблицы стилей, изображения, JavaScript) и шаблоны html, предназначенные для отображения контента в браузере И конфигурационные свойства.
- В каталоге ~/src/main/resources/static/~ хранят статические ресурсы
- В файле ~/src/main/resources/application.properties~ ИЛИ ~/src/main/resources/application.yaml~ описывают *конфигурационные свойства*, но YAML более удобный формат.
  * _Конфигурационные свойства используют для переопределения занчений, присваиваемых механизмом автоконфигурации_.

  * Spring внедряет значения в свойства компонетов, которые хранятся в универсальном хранилище - *откружении Spring*, оно включает следующие /источники/ : переменные среды окружения, аргументы командной строки, application.properties/yaml.

Статический метод ~run(класс_конфигурации, агрументы_командной_строки)~ класса ~SpringApplication~ выполняет фактическую загрузку приложения (вместе со всеми зависимостями), создает контекст приложения ~Spring~.


**** Метаданные проекта

1. Идентификатор группы должен соответствовать соглашениям Java о идентификаторах пакетов. Чтобы сформировать уникальный идентификатор пакета нужно использовать обратное доменное имя организации в качестве префикса для идентифкатора пакета.
   - Доменное имя :: Абстракция над ip адресом, состоит из корневого домена и одного или нескольких компонентов, разделенных точками.
     1. Корневой домен (TLD) % ru, uk, com, org.
     2. Один или несколько компонентов, следующих за корневым доменом. Последовательность от 1 до 63 символов (букв лат. алфавита, цифр и символа -).
2. Идентификатор информационного продукта == идентификатор jar без версии.
   - Диспатчер используется для обработки потока сообщений из тг. Создается с помощью spring boot.



*** Аннотации Spring и Lombok

- @ SpringBootApplication :: Указывается в главном классе приложения. Специализированная форма аннотации ~Configuration~, включает аннотации :
  + @ ComponentScan :: Включает сканирование компонентов - указывает Spring просмотреть все пакеты на уровне главного класса и создать экземпляры классов, помеченных как компоненты контекста приложения Spring.

  + @ Configuration :: Объявляет спец. класс конфигурации, который создает bean-компоненты для контекста Spring.
    * @ Bean :: Определяет методы, _создающие экземпляры компонентов и устанавливающие их свойства_.

      * Имя бина по умолчанию совпадает с именем метода.

      * Этой аннотацией снабжают методы класса конфигурации. Возвращаемые ими объекты должны быть добавлены в контекст приложения как бин-компоненты.

      * Позволяет явно указать Spring какие конструкторы вызывать.

  + @ EnableAutoConfiguration ::

- @ Component :: Основная аннтоция, объявляет класс компонентом контекста приложения Spring.
  + Т. е. если объект класса, объявленного как компонент класса используется другими классами, то _его экземпляры будут созданы автоматически_.

  + Все bean-компоненты можно настраивать с помощью свойств из окружения Spring.


- @ Service ::

- @ Controller ::

- @ Restcontroller ::

- @ ConfigurationProperties ::
  Используется для поддержки внедрения конфигурационных свойств - свойств bean-компонентов.
  + Указывает что значения могут внедряться в свойства bean-компонента из свойств окружения Spring.

- @ Autowired ::
  Явно определяет автоматическое связывание зависимостей.
  + Применяется к свойствам, сеттерам и конструкторам.


- @EventListener


- @Data :: Генерирует во _время компиляции_ сеттеры, гетеры и конструктор для всех свойств класса.
