* Терминология

- underlying platform :: Базовая платформа

- widget :: Элемент графического интерфейса.

- Событие :: Результат любого взаимодействия пользователя с элементами интерфейса : нажатие кнопки, перемещение мыши и т. п.

- pixmap :: Пиксельное изображение.

* Система ресурсов

- Ресурс :: Это файл, используемый приложением на этапе выполнения % изображение, иконка.

  Используемые ресурсы описываются в XML файле с расширением ~.qrc~
  - После добавления ресурса необходимо сохранить файл.

  - Добавляемый ресурс лучше скопировать в папку проекта.


* Структура проекта

Все заголовочные файлы подключаем в заголовочном файле widget.h

Внешний вид приложения настраиваем в файле mainwindow.cpp или widget.cpp


* Классы

** QMainWindow

Каркас для построения пользовательского интерфейса приложения.

** QWidget

Базовый класс для всех элементов пользовательского интерфейса.

** QDialog

Базовый класс для диалоговых окон.

** QIcon

Создает массив пикселей по переданному пиксельному изображению.
