* Терминология

- underlying platform :: Базовая платформа

- widget :: Элемент графического интерфейса.

- Событие :: Результат любого взаимодействия пользователя с элементами интерфейса : нажатие кнопки, перемещение мыши и т. п.

- pixmap :: Пиксельное изображение.

* Система ресурсов

- Ресурс :: Это файл, используемый приложением на этапе выполнения % изображение, иконка.

  Используемые ресурсы описываются в XML файле с расширением ~.qrc~
  - После добавления ресурса необходимо сохранить файл.

  - Добавляемый ресурс лучше скопировать в папку проекта.


* Структура проекта

Все заголовочные файлы подключаем в заголовочном файле widget.h

Внешний вид приложения настраиваем в файле mainwindow.cpp или widget.cpp


* <2023-12-04 Mon> QDesigner

Инструмент, ускоряющий процесс проектирования пользовательского интерфейса.

.ui файл просто xml файл

- callback :: Указатель на ф-цию.
  + Qt предоставляет альтернативу технологии callback - signal & slots

- Событие (Signal)

- Обработчик события (Slot) :: Ф-ция, которая обрабатывает определенный сигнал.
  + Событиям соответствуют сигналы. Определенный сигнал подается когда происходит соответствующее событие.

К виджетам можно добавлять иконки.

Можно как в figma добавлять layout для виджетов.

** Style Sheet

** Horizontal & Vertical Policy

* Классы

** QMainWindow

Каркас для построения пользовательского интерфейса приложения.

** QWidget

Базовый класс для всех элементов пользовательского интерфейса.

** QDialog

Базовый класс для диалоговых окон.

** QIcon

Создает массив пикселей по переданному пиксельному изображению.
