* Спецификация
- Функциональность :: как у paint.
  + НО должнен быть определен набор обектов согласно варианту (у меня планировка кухни), которые масштабируются в зависимости от других объектов

* Ход работы

** Как открыть проект в ide qt creator

- C-o :: Открыть файл или проект, проект описан в файле CMakeLists.txt.

** Как создать графическое приложение

Настроить пользовательские сочетания клавиш можно во вкладке environment.

- C-r :: Собрать и запустить приложение.
- C-q :: Закрыть IDE.
- C-TAB :: Переключаться между исходными файлами.

Файл с разрешением .ui - Графический конструктор как в Windows Forms.

** Как работать с графикой в qt




* Контрольные вопросы [1/8]

- [ ] Зачем нужен перегруженный оператор присваивания ?

  + Чтобы определить операцию глубокого копирования значений свойств одного из объекта в другой
    * Явно определенная операция присваивания необходима если класс содержит свойства типа указатель на некоторый тип.

- [ ] Зачем нужен механизм наследования ?

- [ ] Зачем используются модификаторы при наследовании классов, какие это модификаторы ?

  + Используются чтобы указать режим наследования : открытый, закрытый, защищенный.
    1. Модификатор ~public~ - Означает открытый режим наследования : открытые члены базового класса остаются открытыми в производном классе // Дописать.

    2. Модификатор ~protected~ - Означает защищенный режим наследования : все открытые члены базового класса становятся защищенными членами производного класса.

    3. Модификатор ~private~ - Означает закрытый режим наследования : все члены базового класса становятся закрытыми членами производного класса.
       + Т.е методы базового класса доступны методам производного, но объектам производного не доступны методы базового.


- [ ] Зачем нужен механизм полиморфизма ?


- [ ] Что понимается под динамическим полиморфизмом ?

- [ ] Что такое интерфейс класса ?

- [ ] Зачен нужен чисто виртуальный метод ? Как он выглядит ?

- [X] Какой класс называется абстрактным ?

  + Класс называется абстрактным если его экземляр не может быть создан. Абстрактный класс должен содержать хотя бы один чисто виртуальный метод.
