#+startup: num
* Цитаты автора

* Вынесенные Уроки

- Главное : не уделять слишком много внимания форме и приложению для ведения заметок, а понимать что и для чего я делаю, долой маггизм и беспорядок и в области ведения заметок и управления знаниями.
- Заметка по должна содержать мои собственные мысли и рассуждения по проблеме, указанной в ее заголовке, обоснованные информацией из книг, статей, видео (авторитетных источников).

** стр. 74
    - Нельзя рассматривать процесс организации знаний как самоцель. Не нужно зацикливаться на порядке, надо продолжать развиваться и делиться знаниями. Зафиксированные знания надо использовать для решения задач, не надо тратить много времени на их организацию.

* TODO  Конспект книги
** 🚩 Суть книги
** 🥷 21, - Заметка → кирпичик знаний — самостоятельная единица информации, интерпретируемая с моей точки зрения и хранящееся вне головы — может быть объединен с другими кирпичиками во что-то большее : отчет, рассказ, проект.

- В наше время каждому нужен метод управления информацией.

- Работники интеллектуального труда проводят большую часть времени, управляя большими объемами информации, в этом виде деятельности знания — самое ценное приобретение, так как с помощью них выдвигают новые идеи и решают нестандартные задачи не время от времени, а на постоянной основе.
  + Получение знаний начинается с введения практики ведения заметок.

  + В профессиональной деятельности ведение заметок необходимо, так как от меня ожидается что я буду применять полученные знания на практике, а если я их не зафиксирую, то я их потеряю.

  + "Заметка может включать как цитату из фильма, которая меня действительно поразила, так и тысячи слов, сохраненных из содержательной книги".
    - "Длина и формат не имеют значение, если информационный материал был интерпретирован с моей точки зрения, обработан в соответствии с моим вкусом, изложен моими словами или почерпнут из жизненного опыта, то он является заметкой."
      - Действительно : какой прок переписывать чужие мысли не обработав их в своем уме.

- "Заметки подобны кирпичикам Lego, их можно быстро искать, извлекать, перемещать, собирать и пересобирать, не изобретая ничего с нуля".
  + Их организуют чтобы в тот момент когда потребуется содержащееся в них знание легко его найти и применить для решения задачи.

** 🥷 38 - Метод ~CODE~ → как способ навигации в бесконечном потоке информации, с которым мы сталкиваемся каждый день.

*** WAIT Capture

- (Нельзя превращать хранилище знаний в информационную помойку, которой является интернет) Нужно фиксировать только то, что вызывает резонанс (интеллектуальный отклик) (Capture: Keep What Resonates).
  + Так как мы не можем потребить каждый бит информационного потока, то нужно его ограничить только тем, чем я хочу заполнить свой ум, что мне полезно.
  + =Фиксировать нужно только ценную информацию, а остальное оставить в стороне.=
    a. Ценная информация вызывает интеллектуальный отклик, часто его находят необычные, противоречивые, интересные или потенциально полезные идеи.

  + Введение практики фиксации знаний позволяет избавиться от страха что забудешь что-то важное в решающий момент и сконцентрироваться на получении полезных знаний, сознательно отбросив все остальное.

*** TODO 🥷 72-75 - Organizing for Action. Метод организации знаний в зависимости от их пригодности к применению для решения задач, позволяет быстро отсортировать знания и идеи в соответствии с тем что действительно важно в данный момент времени.

! Ведение заметок не должно отвлекать от основной деятельности (того что интересует сегодня).

=Лучший способ упорядочить цифровые заметки, хранящие зафиксированные знания — упорядочить их по проектам, для  последующего применения=

- Нужно задать вопрос :: "Как эта информация может помочь мне продвинуться в выполнении одного из моих проектов ?".

  + Поскольку : "Информация лучше запоминается когда ты понимаешь для чего она тебе нужна", то когда сосредотачиваешься на решение практических задач (и подходе к организации полученных знаний для последующего их применения) → огромное количество информации радикально *систематизируется* и упрощается.
    a. Практикоориентированный подход к систематизации знаний превращает *процесс систематизации* из препятствия для продуктивности в вклад в нее (contributor to it).

  + =В тот или иной момент времени существует сравнительно немного информации, которая относится к выполняемому делу И является применимой для достижения прогресса в его выполнении.=
    a. Этот подход предоставляет явный критерий отбора информации, который позволяет сконцентрироваться на важном и отбросить все лишнее.

- Фиксация знаний (capturing notes) без эффективного способа их организации и последующего использования приводят лишь к еще большей чрезмерной нагрузке.

- Метод организации знаний и управления ими должен быть тесно внедрен в повседневный рабочий процесс, быть простым, естественным и не отвлекать от основной деятельности.

*** TODO 🥷 94- Distill – Find the Essence

Человеческий разум — раскаленная сковорода ассоциаций, с помощью них одна идея рождает другую. =Каждая заметка — зародыш идеи, напоминающий мне о том, что я уже знаю и думаю по той или иной теме.=

- Чтобы быстро находить ассоциации (закономерности и связи между мыслями и идеями) =нужно свести заметки к их сути= (distill your notes down to their essence).
- Суть даже сложной идеи можно всегда передать в одном-двух предложениях.
  + ⇒ Нужно кратко излагать **основные положения** книги, статьи или видеоролика так, чтобы *главную мысль* было легко определить.

- Действительно, когда срочно потребуется вспомнить важную информацию не будет времени чтобы читать большое количество текста.
  + =Но чтобы освежить в памяти информацию достаточно будет только пробежаться по основным урокам, извлеченным из книги, долгого видео или обширной статьи.=
      
Записывая мысль, нужно задать себе вопрос : "Как я могу сделать ее максимально полезной для себя в будущем ?"
- =Заметки бесполезны, если я не буду к ним обращаться в будущем.=
  + ⇒ Надо дарить себе из будущего знания, которые легко найти, понять и применить в жизнь.

"To attain knowledge, add things every day. To attain wisdom, remove things every day."
- Знание можно обрести если каждый день получать новую информацию по изучаемому предмету.
- Мудрость же можно достичь : анализируя, осознавая, упрощая и отсеивая лишнюю информацию.

Книга подсказок (prompt book) – Техника ведения заметок, которую использовал режисер фильма "Крестный Отец" – Фрэнсис Форд Коппола – он читал роман и записывал эпизоды которые вызывали в нем отклик (эмоциональную реакцию) (resonated with him) вместе со своими мыслями, идеями и инструкциями. Его заметки стали началом процесса пересмотра и доработки исходных материалов (на основе которых создается сценарий, персонажи, сюжет и т.п.), что по итогу позволило Копполе составить сценарий фильма.
- На основе своих заметок Коппола создавал собственную версию истории, он старался изложить суть и смысл каждой сцены одном предложении.

*** WAIT PARA (проекты, области деятельности, ресурсы, архив) :: =Метод организации знаний по их пригодности к использованию для решения той или иной задачи= (по проектам) 4 основные категории информации в нашей жизни.

Суть метода : Позволяет превратить тяжелую бесконечную работу "наведение порядка в заметках" в простую задачу с которой нужно как можно быстрее покончить чтобы перейти к основной деятельности.

      _Проект_ :: [[{{ Проекты  - стр. 76, Building a second brain]]

       _Сфера деятельности_ (вид трудовой деятельности, за выполнение которой я отвечаю) (area) :: [[{{ Сферы деятельности - стр. 78, Building a Second Brain]]

      _Ресурс_  :: [[{{ Ресурсы - стр. 79, Building a Second Brain]]

      _Архив_  :: Склад заметок и ресурсов, которые находятся вне поля зрения (не отображаются в dataview-запросах и в результатах поиска), но в пределах досягаемости.

    Метод PARA можно использовать на любой платформе, его цель — сформировать единую и правильную систему организации чтобы не отвлекаться от основной деятельности и не тратить время впустую.

  - ⇒ Нужно объяснять себе цель фиксации той или иной важной мысли : почему они возникла или привлекла мое внимание.

* Иностранные слова
  
  | Слово               | Транскрипция        | Толкование                                                                  |
  |---------------------+---------------------+-----------------------------------------------------------------------------|
  | Artisan workshop    |                     | Ремесленная мастерская                                                      |
  |                     |                     |                                                                             |
  | broke               |                     | Разориться                                                                  |
  | Capture             |                     | Сбор данных, фиксация                                                       |
  | Clear               |                     | Логический, Явный                                                           |
  | Come across         |                     | Перейти, Сталкиваться с.                                                    |
  | Commonplace book    |                     | Общая тетрадь (для фиксации знаний, изучаемых в рамках различных дисциплин) |
  | Distill             |                     | Извлекать суть, подвергать перегонке.                                       |
  | Distill down to     |                     | Сводить (предельно упрощать)                                                |
  | Essence             |                     | Главное, концентрат, суть                                                   |
  | Eventually          |                     | В итоге                                                                     |
  | Facilitate          | fə'sɪlɪteɪt         | Оказать содействие, упрощать, стимулировать, способствовать осуществлению   |
  | Filter              |                     | Критерий отбора информации                                                  |
  | Haphazardly         | ˌhæp'hæzədli, ərdli | Как-нибудь                                                                  |
  | Idea                |                     | Замысел, мысль, намерение                                                   |
  | Ignore              |                     | Отбрасывать, пренебрегать                                                   |
  | In-depth            |                     | Содержательный                                                              |
  | Insights            |                     | Извлеченные уроки, ценная информация, знания, сущность концепций            |
  | Knowledge worker    |                     | Работник интеллектуального труда                                            |
  | Main point          |                     | Суть дела                                                                   |
  | Main takeaways      |                     | Основные положения, основные уроки                                          |
  | Organizing          |                     | Упорядочивать, систематизировать                                            |
  | Overwhelm           |                     | Забрасывать, ошеломить, перегружать                                         |
  | Realize             |                     | Осознавать                                                                  |
  | Reveal              |                     | Обнаруживать, рассекречивать                                                |
  | Shape               |                     | Непосредственно влиять на, создавать, формировать                           |
  | Streamline          |                     | Систематизировать                                                           |
  | Thing               |                     | Предмет интереса                                                            |
  | Train of thoughts   |                     | Ход мыслей                                                                  |
  | Travel destinations |                     | Туристические направления                                                   |
  | turn down           |                     | Отказаться                                                                  |
  | Use case            |                     | Пример использования                                                        |
  | Utility             |                     | Полезность                                                                  |
