* Языковые средства С++
  - Инструкция ~#include <bits/stdc++.h>~ -> Включает всю стандартную библиотеку.

  ! typedef :: позволяет присвоить сложному типу данных короткое имя.

  ** TODO Побитовые операции 
    - Числа со знаком хранятся в дополнительном коде. 
      + Первый разряд в представлении чисел со знаком содержит знак числа, а остальные n-1 -> абсолютную величину числа.
      + Если данное число больше верхней границы допустимого диапазона, то возникает переполнение.

    - C помощью побитового И можно проверить число на четность. 

    - << Поразрядный сдвиг влево числа x на k разрядов :: Дописывает в конец числа k нулей. Соответствует умножению x на 2^k.

    - >> Поразрядный сдвиг вправо числа x на k разрядов :: Удаляет k последних бит. Соответствует делению x на 2^k
  ** Теория чисел  
    - Если остаток от деления отрицательный, то к нему нужно прибавить число, на которое делим с остатком. 
  ** Ввод/вывод
    - Введенные данные в ввода поток должны быть разделены пробелом или символом новой строки.
    - Считать строку, содержащую пробелы можно с помощью ф-ции getline().
  ** Флаги компилятора g++
    - ~-std~ :: Указывает компилятору стандарт языка. 
    