* Тг бот

- Бот :: Особая учетная запись, небольшое приложение, которое запускается внутри приложения Телеграм, используюет сообщения в качестве входных данных.
  + Главная ф-ция :: отправлять и получать сообщения.
    * Может писать в лс только тем пользователям, которые его запустили.
    * Отправляет запросы на Телеграм и получает от него обновления.
    * Пишутся на Java, js, python с использованием Telegram Bot API или Telegram API (используется больше для создания своего клиента Телеграм) И библиотек.

Создать и настроить бота можно через спец. бота BotFather, он выдает уникальный идентификатор бота, он используется для управления созданным ботом.

* TODO Java [0/1] [0%]

- У меня установлена java 11.

- [ ] Отработать на практике базовый синтаксис и ООП.
  - [ ] Написать алгоритм произведения матриц

** Терминология

- Интерфейс :: Класс, состоит только из чистых виртуальных ф-ций, производный класс может реализовывать несколько интерфейсов.

- Пакет == пространство имен :: Определяет пространство имен классов, позволяет управлять видимостью классов, определенных в нем.
  + Классы одного пакета хранят в каталоге с именем этого пакета.
  + Ключ. слово ~package~ определяет принадлежность к определенному пакету для всех классов в исходном файле.

* Фреймворк Spring

! Установить на ubuntu можно с помощью команды ~apt install spring~, также нужно установить gradle.

- [ ] Разобраться с настройкой проекта spring в vs code.

** Терминология

- bean :: Компонент объектной модели JavaBeans.

- classpath :: Каталог, в котором осуществляется поиск классов.

- Spring Boot :: Расширение фреймворка Java Spring, используется для создания микросервисов. Предоставляет :
  1. Автоконфигурацию, механизм, который позволяет автоматизировать управление контекстом приложения.
  2. Автоматизацию сборки зависимостей
  3. Мониторинг времени выполнения.

- Микросервис :: Маленькая веб-служба выполняет определенные задачи И взаимодействует с другими веб-службами.
  + (разделяй и властвуй) Позволяют разбить большое, сложное монолитное приложение на маленькие, логически независимые модули, что существенно упрощает процессы : разработки, тестирования и развертывания.
  + Приложения на основе микросервисов размещаются в облаке.

- Вебхук == веб-перехватчик :: Механизм получения одним приложением в режиме реального времени информации о событиях, происходящих в другом приложении.
  + Сервер c вебхуком автоматически отправляет клиенту полезную информацию всякий раз когда на серверном приложении происходит определенное событие.
  + Использует протокол HTTP или HTTPS.
    * В целях защиты соединения полезные данные хешируют.


** ? Зачем нужен Spring

В Spring boot проект интегрируют телеграм бота.

Spring создает контейнер == контекст приложения, в котором запускает компоненты приложения (службы) и управляет ими.
- Контекстом приложения управляют с помощью XML-файлов, так и с помощью спец. класса-конфигуратора.
  + В файлах XML описываются компоненты и их взаимосвязи с другими компонентами.

** ? Создание проекта

- Spring Tool Suite :: среда разработки на Spring, расширение для vs code.

- Spring Initializr :: Инструмент инициализации проекта на Spring Boot, Предоставляет REST API.

- Gradle :: Высокопроизводительный иструмент для автоматизации сборки приложений. Выполняется на виртуальной машине Java. Лучше чем Maven.
  + Зависимости добавляются в файл ~build.gradle~.
    - Зависимости :: Модули, библиотеки, необходимые для компиляции приложения.

    - Объявление зависимостей : 1 - в виде строки, 2 - в виде структуры, сост. из пар ключ-значение : группа, имя, версия.
    - Типы зависимостей : 1 - implementation -> используется только для компиляции приложения.


*** Метаданные проекта

1. Идентификатор группы должен соответствовать соглашениям Java о идентификаторах пакетов. Чтобы сформировать уникальный идентификатор пакета нужно использовать обратное доменное имя организации в качестве префикса для идентифкатора пакета.
   - Доменное имя :: Абстракция над ip адресом, состоит из корневого домена и одного или нескольких компонентов, разделенных точками.
     1. Корневой домен (TLD) % ru, uk, com, org.
     2. Один или несколько компонентов, следующих за корневым доменом. Последовательность от 1 до 63 символов (букв лат. алфавита, цифр и символа -).
2. Идентификатор информационного продукта == идентификатор jar без версии.
   - jar :: Архивный файл приложения на языке Java. Используется для хранения приложения Java в одном файле, состоит из скомпилированных в байт-код классов, списка ресурсов и ресурсов приложения.



Диспатчер используется для обработки потока сообщений из тг. Создается с помощью spring boot.

- Брокер сообщений :: Посредник между несколькими частями системы, обеспечивает ассинхронность обработки и распределения сообщений.

Базу данных реализуем на google sheets.

* TODO Изучить синтаксис Java [/] [%]
-
