#+TITLE: Регулярные выражения
* В С++

Для работы с регулярками используется заголовочный файл regex.

- regex_search :: Выполняет в целевой строке поиск подпоследовательности символов, заданной регулярным выражением, возвращает истину если подпоследовательность найдена, иначе ложь.
- regex_match :: Проверяет целевую строку на соответствие подпоследовательности символов, заданной регулярным выражением, возвращает соответственно истину или ложь.

- match_result :: Шаблон класса, который хранит найденную подпоследовательность в целевой строке.
  + smatch -> класс match_result с параметром string.
    - Нулевой индекс : строка, в которой найдена искомая подпоследовательность.
    - Первый и последующие индексы -> соответствуют по порядку подвыражениям, заключенным в круглые скобки.

* Синтаксис
** Круглые скобки
- Скобки выполняют 2 ф-ции : группировка и фиксация.
  + Текст, соответствующий шаблону внутри скобок - фиксируется для дальнейшего использования.
    + Нумеруются слева направо, по открывающим скобкам.