#+TITLE: Мощная и естественная парадигма, используется для создания программ любой сложности.
#+DESCRIPTION: Программа - совокупность взаимодействующих объектов.
* Три принципа :
  - с помощью использвания этих принципов различные части сложной программы могут быть объединены в единое, надежное, сопровождаемое целое. 
  ** Инкапсуляция == изоляция (от лат. : in capsula)
    - Реазиция принципа сокрытия информации Парнаса в ООП. *Механизм*, объединяет данные и методы, работающие с ними, в классе. 
      + Методы обеспечивают открытый интерфейс для взаимодействия объекта с другими объектами системы через интерфейс ввода-вывода.
      + Данные скрываются чтобы исключить возможность произвольного доступа к ним из вне.
  ** DONE Наследование
    ! Отношение обратное наследованию - обобщение.
    ! Чем больше информации, тем хуже управляемость моделированием.
    ! Большинство знаний стало доступно благодаря иерархической классификации.
    - *Механизм*, позволяет описать класс на основе уже существующего, с частично или полностью заимствованной функциональностью.
      + Для производного класса определяются только уникальные свойства и методы, остальное обобщается в базовом классе, что позволяет пограммисту сэкономить время, не писать одно и тоже.
      + Производный класс наследует все свойства и метода предков и прибавляет к ним свои, все они последовательно хранятся в памяти. 
  ** DONE Полиморфизм
    - Полиморфизм реализует принцип "один интерфейс - множество реализаций". Механизм полиморфизма позволяет использовать один интерфейс для "класса" операций, а также использовать объекты с одинаковым интерфейсом, не имея информации об их типах и внутренней структуре.