* TODO ? Область видимости, пространства имен.
* TODO ? Ф-ции И стек
- [ ] Почитать про ф-ции у Кернигана.

* TODO ? Область видимости, пространства имен.

Йозуттис
* TODO Ссылки и Указатели
- [ ] Узнать больше про операторы new & delete.
- [ ] ? Чем отличается NULL от nullptr.

** Страуструп
  Указатели на объекты разных типов имеют разные типы, указатели на объекты базовых и производных классов совместимы по типу.

  Значение одного указателя можно присваивать другому независимо от количества элементов на которые они указывают.

  Инициализировать экземпляр некоторого класса в момент выделения для него динамической памяти можно путем вызова конструктора этого класса. Инициализировать элементы массива можно с помощью списка инициализаторов.

  Память, выделенная оператором new для элементарных типов, не инициализируется.

* TODO <2023-10-12 Thu> ? Параметрический полиморфизм -> Шаблоны И контейенры
** Страуструп

- Шаблон :: Механизм, который позволяет использовать типы в качестве параметров ф-ции или класса.
  + Шаблон класса позволяет использовать заданный в качестве параметра тип для определенных его свойств или методов, который компилятор заменяет на фактический параметр, считываемый из угловых скобок после идентификатора класса, эта процедура выполняется для каждого экземпляра (условно : происходит макроподстановка).
  + Для объявления типа параметра шаблона используются ключевые слова : typename ИЛИ class (они означают одно и то же). Типу параметра шаблона можно присваивать значение по-умолчанию.
  + ~template<typename T>~ означает Для всех типов Т.

** Лафоре
* DONE <2023-10-19 Thu> For-each
** 💿 17- Юзутис
Это цикл, который проходит по всем элементам коллекции

#+BEGIN_SRC C++
  for (const auto& i : коллекция) {
    //Инструкции
  }
#+END_SRC

Неизменяемая ссылка на элемент коллекции позволяет избежать вызова копирующего конструктора и деструктора для каждого из элементов коллекции.

Без использования ссылки инструкции в теле цикла будут оперировать локальными копиями элементов вектора и ни одна из операций над его компонентами не фактически не изменит их.

Эффективная ф-ция вывода элментов коллекции :
#+BEGIN_SRC C++
for (const auto& el : коллекция) {
  cout << el << " ";
}
#+END_SRC

Можно использовать для эффективного перебора списка инициализаторов ~std::initializer_list<>~
* <2023-10-19 Thu> Дружественные ф-ции
** 💿 491- Лафоре
- Объявление друж. ф-ции ИЛИ агрегатного типа данных :: механизм, благодаря которому ф-ция или класс могут получить доступ к *закрытым и защищенным* членам класса, в котором ф-ция или класс объявлены дружественными с помощью ключ слова ~friend~.
  ~ Ф-ция, которая оперирует объектами разных классов.
- Класс String :: Контейнер для ранения символов

** Лафоре
