Для встроенных типов синтаксически (но не технически) определены копирующие конструкторы по умолчанию, вызов которых компилятор переводит в простую инициализацию переменной указанным в скобках (фигурных ИЛИ круглых) значением.

- Класс vector нужно использовать для хранения объектов в куче, а класс array - для хранения объектов в стеке или в сегменте данных.
  + Класс array в отличие от массивов является *безопасным с точки зрения прямого доступа*, так как хранит размер внутреннего массива, что позволяет предотвратить выход за границы множества индексов.

- [ ] Узнать больше про списки инициализаторов
- [ ] Разобраться с конструктором перемещения (18.3).

* Списки инициализаторов И списочная инициализация

** Скот Мейерс

- Если объект агрегатного типа данных (массив, структура, класс) ТО выполняется агрегатная инициализация, ИНАЧЕ : выполняется обычная инициализация копированием, вызывается конструктор копирования.

- Фигурные скобки используются для явного вызова конструктора по умолчанию (без параметров)

- Для того чтобы отличить синтаксически отличать присваивание от инициализации в стандарте С++11 введена синтаксическая конструкция "список иницилизаторов". Список инициализаторов заключается в фигурные скобки (braces).

* DONE ? Стандарты С++

- mature :: Созреть, сформироваться

- C++11 :: Второй ISO стандарт языка С++. В нем описывается синтаксис языка и возможности стандартной библиотеки. Кто угодно может предложить новые ф-ции и расширения стандартной библиотеки, но чтобы они стали частью языка, они должны быть приняты всей организацией по стандартизации.

* WAIT Область видимости, пространства имен.
* HOLD Ф-ции, методы и стек

** <2023-10-19 Thu> Дружественные ф-ции
*** 💿 491- Лафоре
- Объявление друж. ф-ции ИЛИ агрегатного типа данных :: механизм, благодаря которому ф-ция или класс могут получить доступ к *закрытым и защищенным* членам класса, в котором ф-ция или класс объявлены дружественными с помощью ключ слова ~friend~.
  ~ Ф-ция, которая оперирует объектами разных классов.

* WAIT C++11 Ссылки и семантика перемещения
* WAIT Указатели И динамически распределяемая область памяти

! Указатели на базовый и производный класс совместимы по типы, НО базовый и производный классы не совместимы по типу.

** Оператор new -> Выделяет память
! Возвращает указатель на адрес первого байта выделенной области памяти.

- Синтаксис :: для объекта : ~new Тип{Список инициализации}~, для массива объектов : ~new Тип[размер]{список_инициализаторов}~.

** Оператор delete -> Освобождает память

- Синтаксис :: для объекта : ~delete Указатель~, для массива объектов : ~delete[] Указатель~.

* WAIT <2023-10-24 Tue> Конструкторы и деструкторы
# Краткое и всеобъемлющее изложение информации из нескольких источников
* TODO <2023-10-12 Thu> Полиморфизм
** Параметрический полиморфизм -> Шаблоны - Позволяет использовать единый интерфейс, определяемый классом, для работы объектами, хранящими или обрабатывающими объекты разных, более элементарных, типов. Полезно сочетать с динамическим полиморфизмом.
*** Страуструп 💿

Используются для создания гибких и высокопроизводительных программ (параметрический полиморфизм более производительный чем динамический полиморфизм)

- Обобщенное программирование == Алгоритмически ориентированное программирование :: Процесс создания кода, работающего с разными типами, заданными в виде параметров, эти типы должны соответствовать специфическим синтаксическим и семантическим требованиям.
  + Сначала следует разработать и протестировать класс, используя конкретные типы, а потом заменить их параметром шаблона.
    * Шаблон :: Механизм, который позволяет использовать типы в качестве параметров ф-ции или класса.

      1. Шаблон класса == генератор типов -> позволяет использовать заданный в качестве параметра тип для определенных его свойств или методов, который компилятор заменяет на фактический параметр, считываемый из угловых скобок после идентификатора класса, эта процедура выполняется для каждого экземпляра (условно : происходит макроподстановка).

      2. Для объявления типа параметра шаблона используются ключевые слова : ~typename~ ИЛИ ~class~ (они означают одно и то же). Типу параметра шаблона можно присваивать значение по-умолчанию.

      3. ~template<typename T>~ означает Для всех типов Т.

  + Специализация :: Процесс создания классов/ф-ций из шаблона класса/ф-ции по заданным параметрам шаблона. Осуществляется на этапе компиляции или на этапе компоновки.

  + Параметризация :: Подстановка конкретного типа в шаблон.
    * Шаблон ф-ции == Алгоритм.

- Концепция :: Множество требований к параметру шаблона.

- Компилятор определяет параметры шаблона ф-ции по фактическим параметрам ф-ции. Но вообще : ~Ф-ция<параметры_шаблона>(фактические_параметры)~

*** Лафоре
** Статический полиморфизм -> Перегрузка ф-ций и методов
** Динамический полиморфизм -> Переопределение методов в производных классах (Виртуальные ф-ции)

* DONE <2023-10-19 Thu> For-each

** 💿 17- Йозуттис
Это цикл, который проходит по всем элементам коллекции

#+BEGIN_SRC C++
  for (const auto& i : коллекция) {
    //Инструкции
  }
#+END_SRC

Неизменяемая ссылка на элемент коллекции позволяет избежать вызова копирующего конструктора и деструктора для каждого из элементов коллекции.

Без использования ссылки инструкции в теле цикла будут оперировать локальными копиями элементов вектора и ни одна из операций над его компонентами не фактически не изменит их.

Эффективная ф-ция вывода элментов коллекции :
#+BEGIN_SRC C++
for (const auto& el : коллекция) {
  cout << el << " ";
}
#+END_SRC

Можно использовать для эффективного перебора списка инициализаторов ~std::initializer_list<>~
