#+title:  Qt C Фреймворк
- Для написания GUI приложений на С++ используют фреймворк ImGui или wxWidgets. Для редактирования изображений OpenCV.
  + [[https://github.com/ocornut/imgui/wiki][Документация]]

- Qt :: Набор средств разработки кросплатформенных графических приложений на С++.

- Установщик позволяет установить библиотеки, ide, документацию, исходный код, модули.
  + Онлайн установщик скачивает все необходимые для установки файлы.
  + Оффлайн уставновщики не доступны начиная с версии qt 5.15.

- Библиотека Qt и Qt Creator загружаются с репозитория git и собираются отдельно с помощью cmake.

* TODO Изучить cmake

- build :: Сборка - процесс преобразования исходного кода (часто в нескольких исходных файлах) в исполняемый файл путем компиляции исходых файлов и компоновки объектных файлов и библиотек.
- build system :: Система сборки проекта.


- target :: Понятие, представляет выходной файл сборки (build aftifact) % исполняемый файл, библиотека.

- Средство автоматизации сборки позволяет скомпилировать исполняемый файл или библиотеку из множества исходных файлов. Разделяет каталог проекта на каталог исходных файлов и на каталог двоичных файлов. CMake записывает объектные файлы, библиотеки и исполняемые файлы в каталог двоичных файлов.
  + Файлы CMakeLists.txt содержат описание проекта на языке cmake.
    * Файл CMakeLists.txt в корневом каталоге проекта содержит спецификацию сборки проекта.
    * CMake создает проект
    * Пользователь выполняет сборку проекта

- cmake build :: Выполняет сборку проекта на основе созданного двоичного дерева проекта.
- cmake install <Каталог_двоичных_файлов_проекта> :: Перемещает созданные выходные данные сборки % исполняемые файлы и библиотеки, в определенные системные каталоги.
  - --prefix :: Изменяет каталог, в который будут перемещены результаты сборки.

- Инструмент используется gcc по умолчанию.
