* TODO ? Область видимости, пространства имен.
* ? Итераторы
* ? Контейнеры
 - Контейнер последовательности

* TODO <2023-10-12 Thu> ? Параметрический полиморфизм -> Шаблоны
** Страуструп

- Шаблон :: Механизм, который позволяет использовать типы в качестве параметров ф-ции или класса.
  + Шаблон класса позволяет использовать заданный в качестве параметра тип для определенных его свойств или методов, который компилятор заменяет на фактический параметр, считываемый из угловых скобок после идентификатора класса, эта процедура выполняется для каждого экземпляра (условно : происходит макроподстановка).
  + Для объявления типа параметра шаблона используются ключевые слова : typename ИЛИ class (они означают одно и то же). Типу параметра шаблона можно присваивать значение по-умолчанию.
  + ~template<typename T>~ означает Для всех типов Т.



** Лафоре
* DONE <2023-10-19 Thu> For-each
** 💿 17- Юзутис
Это цикл, который проходит по всем элементам коллекции

#+BEGIN_SRC C++
  for (const auto& i : коллекция) {
    //Инструкции
  }
#+END_SRC

Неизменяемая ссылка на элемент коллекции позволяет избежать вызова копирующего конструктора и деструктора для каждого из элементов коллекции.

Без использования ссылки инструкции в теле цикла будут оперировать локальными копиями элементов вектора и ни одна из операций над его компонентами не фактически не изменит их.

Эффективная ф-ция вывода элментов коллекции :
#+BEGIN_SRC C++
for (const auto& el : коллекция) {
  cout << el << " ";
}
#+END_SRC

Можно использовать для эффективного перебора списка инициализаторов ~std::initializer_list<>~
* <2023-10-19 Thu> Дружественные ф-ции
** 💿 491-500 Лафоре
- Объявление друж. ф-ции ИЛИ агрегатного типа данных :: механизм, благодаря которому ф-ция или класс могут получить доступ к *закрытым и защищенным* членам класса, в котором ф-ция или класс объявлены дружественными с помощью ключ слова ~friend тип_возвр _значения сигнатура~ ИЛИ ~friend class идентификатор~.
  ~ Ф-ция, которая оперирует объектами разных классов, чтобы явно задать типы операндов.
  + Дружественные ф-ции должны использоваться как можно реже.
* <2023-10-19 Thu> Статические методы
** 💿 500- Лафоре


* Автоматическое определение типов
** 💿 14 Юзутис
- Компилятор определяет тип переменной, объявленной без явного указания типа по ее иницализаторy.
** 💿 800 Страуструп
- Строковый литерал всегда имеет тип ~const char*~
- Можно спокойно использовать в тех случаях когда знаю какой тип будет иметь объект в результате выражения.
