#+TITLE:
* Избранное

! Чтобы установить emacs на Linux надо ввести команду ~sudo apt install emacs28~

* Конспект
** 🐝 07.10.23 💿️ 19- Начало пути
*** WAIT Буферы

- C-x h :: Выделить весь текст в буфере.

**** Major mode буфера :: определяет подсветку синтаксиса, спец. команды
+ Определяется emacs по расширению файла ИЛИ если у файла неоднозначное расширение, по его содержимому.
+ Всегда отображается в строке состояния
+ Font Locking == подсветка синтаксиса в emacs.
**** Minor mode буфера :: Просто все дополнения, включенные для данного буфера.

+ В строке состояния отображаются только те второстепенные режимы, которые как то изменяют буфер или взаимодействие с ним.

***** CC Mode

+ ~C-c C-c~ -> Закоментировать строку;

** Сочетания клавиш

- Сочетание клавиш :: Формально определенная последовательность нажатий на клавиши клавиатуры или мыши, которая вызывает соответствующую команду.

- Клавиша модификатор :: Клавиша, которая временно изменяет действие другой при одновременном нажатии.

- Модификатор M :: Означал  клавишу Meta на клавиатуре space-cadet, на современных пк префикс M означает клавишу Alt.

- C-x C-f -> find-file :: Найти файл
- C-M-% -> query-replace-regexp :: Поиск и замена
- C-g :: Отменить команду

! При вводе команды лучше не отпускать клавиши-модификаторы.

** TODO Конфигурация emacs
