#+TITLE:
* Мои примечания
* Примечания автора
* Конспект
** DONE 01.10.23 💿 52, -> Пробельные символы И литералы
  - 1 шаг табуляции == 8 пробельных символов.
  - cin :: Ключевое слово, объект (instream), определенный для работы с стандартным потоком ввода, который содержит вводимые с клавиатуры данные.
  - endl :: Выполняет вставку управляющей последовательности (escape character) → новой строки ~\n~ И сбрасывает буфер стандартного потока вывода.
  - setw(n) :: Изменяет ширину поля вывода, выводит число или строку, сл. за ним в потоке в поле, шириной в n символов.
    + Объявлен в заголовочном файле ~iomanip~.
  - В одинарных кавычках записывают символьные литералы, в двойных → строковые.
    - Компилятор заменяет всякую символьный литерал (букву) на соответствующий ASCII код.
  - "Компилятор игнорирует пратически все пробельные символы" текстовых файлов : { пробел, переход на другую строку, верт. И гор. табуляция, возврат каретки } ( если они не являются компонентами строковых литералов, для разделения строковых литералов исп. символ ~\~ ) , так как они УДАЛЯЮТСЯ при предварительной обработке текста программы. НО : директива препроцессора ~include~ должна быть записана в одну строку.
  - Переменная типа bool занимает в памяти 1 байт.
  - \ :: управляет интерпретацией следующего за ним символа.
  - Экспонента в экспоненциальной форме записи числа с плавающей точкой показывает на сколько знаков нужно переместить число, следующее за знаком e чтобы вернуть число к нормальной десятичной форме.
    - Используется чтобы не выписывать большое количество нулей.
** DONE 23.09.23 💿 228-236 — Конструктор и деструктор
  - Конструктор :: особый метод класса, вызывается компилятором автоматически  в момент создания объекта, для инициализации его полей. 
    + Инициализацию полей класса выносят в список инициализации, чтобы она была выполнена до начала выполнения инструкций тела конструктора. ~Идентификатор_класса() : поле1{Список_инициализаторов}, ... { тело конструктора }~
    + У каждого стандартного типа данных есть собственный конструтктор, который выделяет для них определенное количество байт памяти.
    + Компилятор автоматически встраивает в программу конструктор  по умолчанию (без параметров) и копирующий конструктор по умолчанию (принимает в качестве параметра объект того же класса, и инициализирует создаваемый объект его значениями), который инициализирует атрибуты. ~Ид_Класса объект2(объект1), объект3 = объект1;~
    - Деструктор :: Особый метод класса, вызывается компилятором автоматически в момент выхода объекта за область своего действия, для освобождения памяти, выделенной конструктором при создании объекта.
    - Прототип ф-ции :: объявление ф-ции без определения тела функции, включает :  спецификатор доступа, тип возвращаемого значения, идентификатор, список параметров (сигнатуру).
  ** DONE Виртуальные ф-ции
    - Назначение :: Позволяют выполнять операции с помощью одного выражения над объектами разных классов => использование вирт. ф-ций -> один из способов достижения полиморфизма.
      + Адреса объектов производных от абстрактного класса классов удобно хранить в массиве указателей на базовый абстрактный класс.
    - Абстрактный класс :: Класс, включает хотя бы одну чистую виртуальную ф-цию, и соответственно не может иметь экземпляров, используется в качестве звена иерархической структуры группы классов.
    - Чистая виртуальная функция ::  виртуальная функция, после объявления которой добавлена конструкция =0, она указывает компилятору : объект такого класса нельзя создать.
      + Ключевое слово virual :: указание компилятору искать реализацию метода базового класса в производном классе.
      + Виртуальный :: видимый, но не существующий в реальности.
    - Указатель на производный класс совместим по типу с указателем на базовый класс.
      + В этом случае компилятор НЕ выполняет проверку И преобразование типов.
      + Виртуальный деструктор вызывает деструктор И для производного И для базового класса, используются чтобы убедиться что память под объекты производных классов освобождается так, как нужно.
** TODO Виртуальны базовые классы   
  - Виртуальные базовые классы используются для множественного наследования. 
    - [n] Для каждого из производных классов выделяется память под поля базовых классов (т.к. наследование – просто абстракция, нужна чтобы упростить программисту работу над большими проектами, повысить читаемость программы)
