- LTS :: С долгосрочной поддрежкой.
- Класс - спецификация, объект - реализация
* Особенности Java
** <2023-10-16 Mon> 💿 История языка

- Java разработан из-за необходимости в архитектурно-нейтральном языке, на котором можно писать ПО, для бытовых электронных устройств.
  + С распространением интернета потребность в переносимом ПО только возросла, так как в сети необходимо и запускать одну и ту же программу на разных платформах.
  + Не обладает ни прямой, ни обратной совместимостью с С++, с создан для решения одних задач, С++ - для других.

В Java простой синтаксис и высокий уровень абстракции, НО нужно уметь использвать классы стандартных и сторонних библиотек.
Каждая программа на Java соответствует парадигме ООП.

Java чувствиетелен к регистру.

** Отличия от С++

a. Отсутствует автоматическое преобразование типов, несоответствие типов - ошибка времени компиляции.

b. Запрешено использование оператора безусловного перехода goto.

c. Индентификатор, вкл. ~-~ явл. недопустимым.

d. Все элементарные типы данных имеют строго определенный диапазон значений.

e. НЕТ беззнакового целого типа.

f. Для представления символов используется кодировка Unicode, первые 127 кодов выделены для символов кодировки ASCII.
   + => Тип char занимает 2 байта.

** TODO <2023-10-16 Mon> 💿 Байткод, JVM [0/1] [0%]

- [ ] Узнать больше о структуре JVM.

- Байткод :: Оптимизированный набор инструкций, предназначенных для выполнения виртуальной машиной Java (интерпретатор байт-кода), которая является частью среды выполнения Java (JRE).

Использование виртуальной машины упрощает запуск программы на разных платформах, так как для каждой из них нужно реализовать только JVM, которая принимает один и тот же байт-код, это позволяет не переписывать компилятор для каждого типа процессоров.

Виртуальная машина позволяет создать ограниченную в ресурсах среду выполнения программы - песочницу

В состав JVM входит JIT компилятор для байт-кода, он позволяет скомпилировать во время выполнения (по запросу) часть байт кода в машинный код, с целью повышения производительности. Остальной байт-код интерпретируется.


* Ответы на вопросы
** В языках, производных от С
- , :: Означает список объявлений объектов одного типа.
- {} :: Групповой оператор, с его помощью объединяют от 2х инструкций в блоки.

** ? Для чего сейчас применяется Java

Сечас Java в основном используется для написания сервлетов.

- Сервлет :: Программа, исполняется на сервере.
  + Используется для формирования динамически-создаваемого содержимого веб-страницы, на основе действий клиента (сервера), которая отправляется браузеру.

** ? Скомпилировать и запустить программу на Java

> Скомпилировать -> вызывав для исходного файла компилятор ~javac~, Выполнить -> загрузить байткод в JVM, вызвать загрузчик ~java~.

Расширение файла с исходным кодом Java : ~.java~

Один класc - один файл, весь код должен находиться внутри классов. Имя главного класса должно совпадать с именем файла вплоть до регистра.

- Программа javac :: Компилятор языка программирования Java, переводит исходный код на Java в инструкции виртуальной машины (байт код) Java.
  + Для каждого класса создает отдельный файл, с именем класса и расширением ~.class~.

- Программа java :: Программа запуска приложений Java, запускает среду выполнения Java, загружает указанный класс (файл с расшинением .class) в JVM. Метод main -> точка входа в программу, сост. из одного или нескольких классов.
  - Метод main должен :
    1. Быть открытым
    2. Быть статическим
    3. Принимать в качестве параметра массив типа String.
       + Хранит любые аргументы командной строки.

* Терминология

- Online world :: Виртуальный мир.
- Web programming :: Программирование приложений для интернета.

- Единица компиляции :: файл с исходным кодом Java.

* TODO <2023-10-17 Tue> Синтаксис [0/1] [0%]
- [ ] стр. 147-148 : цикл for и использование запятой, for-each.

- var == auto В С++, компилятор сам определит тип значения выражения.

4 элем. типа данных, предств. целые числа :
| Ключ. слово | Разрядность (в битах) |
|-------------+-----------------------|
| long        |                    64 |
| int         |                    32 |
| short       |                    16 |
| byte        |                     8 |

** Комментарии

1. Однострочные
2. Многострочные
3. Используемый для создания документации

* Основные инструменты
** TODO Ввод и вывод

- [ ] Разобраться с классом scanner.

*** Ввод

Класс Scanner содержится в пакете java.util, считывает текст из источника, который реализует интерфейс Readable, разбивает текст на лексемы по заданным разделителям и преобразует их в значения с помощью методов next ИЛИ с помощью регулярных выражений, определяющих формат входных данных.

*** Вывод
- Статический метод println() :: Принимает строку, к строке можно добавить переменную элементарного типа с помощью перегруженного оператора ~+~, вставляет символ новой строки в поток вывода;
  + Если строка, добавленная в стандартный поток вывода не оканчивается символом новой строки, то следующая строка добавится в ту же строку стандратного потока вывода.

- print :: не вставляет символ новой строки в поток вывода.

* TODO ООП [0/1] [0%]
- [ ] стр. 163 ООП
