* Примечания

! В Java простой синтаксис и высокий уровень абстракции, НО нужно уметь использвать классы стандартных и сторонних библиотек.

- Каждая программа на Java соответствует парадигме ООП.
! Java чувствиетелен к регистру.

- Расширение файла с исходным кодом Java : ~.java~ 
! Один класса - один файл, весь код должен находиться внутри классов. Имя главного класса должно совпадать с именем файла вплоть до регистра.

- Программа javac :: Компилятор языка программирования Java, переводит код на Java в инструкции виртуальной машины (байт код) Java. 
  + Для каждого класса создает отдельный файл, с именем класса и расширением ~.class~.

- Программа java :: Программа запуска приложений Java, запускает среду выполнения Java, загружает указанный класс (файл с расшинением .class), вызывает метод main этого файла.
  - Главный метод должен : 
    1. Быть открытым
    2. Быть статическим
    3. Принимать в качестве параметра массив типа String.
      + Хранит любые аргументы командной строки.

- Единица компиляции :: файл с исходным кодом Java.

* 3 типа комментариев
  
  1. Однострочные
  2. Многострочные
  3. Документирующие

* Ввод и вывод

  - ! Если строка, добавленная в стандартный поток вывода не оканчивается символом новой строки, то следующая строка добавится в ту же строку стандратного потока вывода. 

* TODO ? Что такое Java VM, JDK
- Класс - спецификация, объект - реализация
