* А
** Абстракция и абстрагирование
- От латинского : отвлечение, отделение.

- Управление абстракцией :: ==процесс выбора и использования наиболее подходящих абстракций для решения конкретной задачи или проблемы.==

- Абстрагирование :: Процесс определения существенных и значимых в рамках поставленной задачи характеристик некоторой сущности И представление их в терминах языка программирования.
  + Абстракция :: Результат процесса абстрагирования.
  + В ООП механизмы управления абстракцией : полиморфизм, наследование, инкапсуляция.
  + В ООП рассматривается абстракция данных, которая подразумевает набор наиболее значимых характеристик объекта, доступных и используемых в программе.
* К
- Коллекция :: Реализация соответствующего атд, структура данных, хранит множество элементов и предоставляет методы для управления ими.

- Контейнер :: Любой тип данных, используемый для хранения элементов и управления ими. Для разных задач существуют разные контейнеры. 
  + Контейнер НЕ обязательно должен быть коллекцией.

* Л
- Литерал :: Явно заданное в тексте программы, неименованное значение определенного элементарного типа данных % логический, числовой, строковый, символьный, шаблонный.

* М
- Метаданные :: Описывают структуру данных
  % В С/С++ за метаданные описывают с помощью аггрегатных типов данных.

* П
- Парадигма (paradigm) ::  Совокупность принципов, методов и понятий, определяющих  определяющий способ конструирования программ и организацию вычислительной работы, выполняемой компьютером. 
  + Определяется : вычислительной моделью, механизмами управления абстракцией, элементарными единицами модульности. 

* Р
- Разработка :: Процесс проектирования и создания ПО, которое служит опр. цели и

* С
- Сигнатура ф-ции :: Идентификатор + список формальных параметров.

- Структура :: Множество элементов и множество связей между ними.

- Сущность :: Тип объекта реального мира, описываемого с помощью средств используемого языка программирования.

* Ф
- Фреймворк :: Набор библиотек классов, написанных на определенном ЯП. Предоставляет готовые решения для определенного множества задач.

* E
- enumeration :: Перечень.
