* А
** Абстракция и абстрагирование
- От латинского : отвлечение, отделение.

- Управление абстракцией :: ==процесс выбора и использования наиболее подходящих абстракций для решения конкретной задачи или проблемы.==

- Абстрагирование :: Процесс определения существенных и значимых в рамках поставленной задачи характеристик некоторой сущности И представление их в терминах языка программирования.
  + Абстракция :: Результат процесса абстрагирования.
  + В ООП механизмы управления абстракцией : полиморфизм, наследование, инкапсуляция.
  + В ООП рассматривается абстракция данных, которая подразумевает набор наиболее значимых характеристик объекта, доступных и используемых в программе.
* П
- Парадигма (paradigm) ::  Совокупность принципов, методов и понятий, определяющих  определяющий способ конструирования программ и организацию вычислительной работы, выполняемой компьютером. 
  + Определяется : вычислительной моделью, механизмами управления абстракцией, элементарными единицами модульности. 

* С
- Сущность :: Тип объекта реального мира, описываемого с помощью средств используемого языка программирования.
* E
- enumeration :: Перечень.
